<%
arrTYPESWORDS = Split("STR,ARQUIVO,STR,STR,ARQUIVO,STR,STR,STR,CHAVE,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,NUM,STR,NUM,STR,STR,STR,NUM,NUM,DATE,STR,STR,STR,STR,STR,STR,DATE,DATE,DATE,DATETIME,DATE,DATETIME,DATE,DATE,DATE,DATETIME,DATETIME,DATETIME,DATE,DATE,EMAIL,STR,STR,STR,STR,STR,STR,STR,STR,MOEDA,STR,STR,STR,MOEDA,STR,STR,STR,STR,STR,STR,STR,INT,INT,STR,STR,MOEDA,MOEDA,MOEDA,STR,STR,INT,INT,STR,STR,STR,STR,STR,STR,STR,STR,STR,STR,LINK,STR,STR,DATETIME,STR,STR,STR,STR,INT,STR,MOEDA,MOEDA,MOEDA,MOEDA", ",")
%>
